baseURL = 'https://spine.io/'
languageCode = 'en-us'
title = 'Spine Event Engine'

[module]
  [[module.imports]]
    path = 'github.com/TeamDev-Ltd/site-commons'
  [[module.imports]]
    path = 'github.com/SpineEventEngine/documentation/_hugo-theme'

[params.libs.docsearch]
  appId = 'DUYV0WFHKV'
  apiKey = '50ce4ead490484f1436ae042c0a1a4dd'
  index = 'spine'

[security]
  [security.exec]
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME)$']

# Enables HTML rendering in markdown files.
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

# Version control config.
# To change the current main version, update only the `path` parameter.
# Read more in the `SPINE_RELEASE.md` guide.
#
# The configuration is duplicated now due to the known issue with cascade arrays:
# https://github.com/gohugoio/hugo/issues/13869
[[cascade]]
  [cascade.params]
    url = 'docs/'
  [cascade.target]
    # The path to the `_index.md` of the current main version.
    path = '{/docs/1}'
    kind = 'section'
[[cascade]]
  [cascade.params]
    url = 'docs/:sections[2:]/'
  [cascade.target]
    # The path to the current main version.
    path = '{/docs/1/**}'
    kind = 'section'
[[cascade]]
  [cascade.params]
    url = 'docs/:sections[2:]/:contentbasename/'
  [cascade.target]
    # The path to the current main version.
    path = '{/docs/1/**}'
    kind = 'page'
